### ISSUE TITLE
filters still flaky..

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#23]
was looking in FOX_DATA.debug 

![image](https://user-images.githubusercontent.com/713166/54167705-6932a300-4441-11e9-998b-c58ccd3609a2.png)

utils.js:152 Uncaught TypeError: data.forEach is not a function
    at Object.parseDataToViews (utils.js:152)
    at h.<anonymous> (mainService.js:266)
    at h.callEvent (webix.js:23)
    at h.Bg (webix.js:633)
    at h.select (webix.js:634)
    at h.webix_tree_item (webix.js:722)
    at h.Yc (webix.js:284)
    at h.Sc (webix.js:280)
    at HTMLDivElement.<anonymous> (webix.js:13)
parseDataToViews @ utils.js:152
(anonymous) @ mainService.js:266
callEvent @ webix.js:23
Bg @ webix.js:633
select @ webix.js:634
webix_tree_item @ webix.js:722
Yc @ webix.js:284
Sc @ webix.js:280
(anonymous) @ webix.js:13
2metadataTableModel.js:218 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at compareMetadataColumnFilter (metadataTableModel.js:218)
    at compare (metadataTableModel.js:143)
    at h.<anonymous> (webix.js:1011)
    at webix.js:13
    at webix.DataStore.Bf (webix.js:552)
    at webix.DataStore.filter (webix.js:554)
    at h.filter (webix.js:555)
    at h.<anonymous> (webix.js:1011)
    at webix.DataStore.silent (webix.js:535)
    at h.filterByAll (webix.js:1010)
compareMetadataColumnFilter @ metadataTableModel.js:218
compare @ metadataTableModel.js:143
(anonymous) @ webix.js:1011
(anonymous) @ webix.js:13
Bf @ webix.js:552
filter @ webix.js:554
(anonymous) @ webix.js:555
(anonymous) @ webix.js:1011
silent @ webix.js:535
filterByAll @ webix.js:1010
Vk @ webix.js:1005

**Comment by dverkhovsky13** [comment]
Fixed in last PR. You can check and say if anything is not working. Thank you.

**Comment by sraja2911** [comment]
With the latest pull (03/13), it looks like filter is not working. 
![image](https://user-images.githubusercontent.com/8167331/54303448-6054e500-4599-11e9-8720-61fe42a5e939.png)

**Comment by dverkhovsky13** [comment]
Have you tried to clean localStorage? Cuz I'm testing it right now with the same folder and everything works.

**Comment by sraja2911** [comment]
No, still does not work...
![image](https://user-images.githubusercontent.com/8167331/54386033-7385b480-466e-11e9-96d8-335ba2d0bc99.png)

**Comment by sraja2911** [comment]
Need to refresh/reload the webpage again, even after removing the selected filter values (the concerned filter value is not available in the database). 
1. For eg, add select filter (BrainID) and change the value to "Test" from existing value on a single row
2. Change it back to existing  value
3. Select filter will show all the values, including non-available values

In the following screen : "ghjhggh" is removed, but still shows the select filter.

![image](https://user-images.githubusercontent.com/8167331/54393204-f6633b00-467f-11e9-9398-89172b563ba5.png)

**Comment by dgutman** [comment]
I'll double check the cache thing with Raj in the am..

**Comment by dverkhovsky13** [comment]
localStorage.clear() not localStorage.clear. You forgot to call the function.

**Comment by sraja2911** [comment]
localStorage.clear() - undefined (in chromium and chrome)
![image](https://user-images.githubusercontent.com/8167331/54442064-54416280-4714-11e9-8904-0b6dbf7109f3.png)

**Comment by sraja2911** [comment]
select filter is not working.

Below selected BrainID->FOX56A filter, still shows FOX17U rows.

![image](https://user-images.githubusercontent.com/8167331/54443159-72a85d80-4716-11e9-9fae-ee25e0f554ad.png)

**Comment by dverkhovsky13** [comment]
I still can't see the bug with filters. Did you debug on 93.85.94.98:10353?

**Comment by dverkhovsky13** [comment]
Clear all cookies and localStorage before you even testing please. And send me a video of the bug, if you can, this would be helpful.

**Comment by dgutman** [comment]
Dimitry I'll test again.. also I added data to dermannotator under lesion
images.. the metadata table wasn't loading properly .. I'll post more info
shortly..

**Comment by sraja2911** [comment]
It does not work on local system, which I pulled out from Github. It works on 93.85.94.98:10353.

**Comment by dverkhovsky13** [comment]
Code on 93.85.94.98:10353 is the same as I gave you. I can't tell if you changed anything but obviously it's something you have done with code, anything including merging new code to your changed one.

**Comment by sraja2911** [comment]
It works at your server and with code from your github. Can not expect user to refresh entire web page or keying the function localStorage.clear() in javascript console, every time. Can you do page-refresh, page-cleanup within the code itself, so that user can see the results dynamically without any user-intervention?
